spring.application.name=wordprocessor

# Set the max request size to 10KB for testing purposes
server.tomcat.max-http-post-size=10240

# Default Business Rules
app.rules.default.count-condition=STARTS_WITH
app.rules.default.count-value=m
app.rules.default.collect-condition=LENGTH_GREATER_THAN
app.rules.default.collect-value=5